### PR TITLE
UI enhancement for the navbar

### PR DESCRIPTION
**Pull request by shrey1608**
Changed the UI for the navbar
Also updated the code from bootstrap3 to bootstrap 4 (please provide points for that too)

### CODE REVIEW

**Comment by ExpressHermes** [comment]
@shrey1608 can you share them image of the navbar here?

**Review by ExpressHermes — COMMENTED** [review]
Also I noticed you are not using template inheritance. You have seperate head tag in index and login.

**Comment by shrey1608** [comment]
> Also I noticed you are not using template inheritance. You have seperate head tag in index and login.

Ohh ya i forgot that will make a commit for it

**Comment by shrey1608** [comment]
nav
ignore the body background just took a dummy to see it fits properly or not @ExpressHermes

**Comment by ExpressHermes** [comment]
You need to align the nav items in middle. The bgcolor of navbar can be further improved. Color of the links is black which is not good since the background is dark colored.

**Comment by shrey1608** [comment]
ok i will align the nav items in the middle. Can you suggest any color ? ok i will make the links light @ExpressHermes

**Comment by ExpressHermes** [comment]
https://www.happyhues.co/palettes/3

Experiment with the colors here and decide something.

**Comment by shrey1608** [comment]
image
is this looking good?(The color) @ExpressHermes

**Comment by shrey1608** [comment]
If it looks fine please merge it @mann27 @ExpressHermes

**Review by ExpressHermes — APPROVED** [review]
Although the links are yet not properly aligned in the middle due to the brand name's large size. I will merge it.

**Comment by ExpressHermes** [comment]
~give @shrey1608 50 points~ 

Leaving it for reference. But invalid points. Updated them below.

**Comment by mann27** [comment]
@ExpressHermes we cannot give 50 points!
change it to 25 or 75 points.

**Comment by ExpressHermes** [comment]
give @shrey1608 25 points

**Comment by ExpressHermes** [comment]
give @shrey1608 25 points

**Pull request merged**
