### PR TITLE
[WIP] Adding star/favourite feature

### PR DESCRIPTION
**Pull request by ExpressHermes**
Needs to be reviewed for errors! I am reviewing it

### CODE REVIEW

**Comment by ExpressHermes** [comment]
@shrey1608  These are the issues you need to address:

- In `views.py`:
   - You are not importing JsonResponse used in `favAlbum`. To import it:
    ```
    from django.http import JsonResponse
    ```
    - In the `favAlbum` view, you were sending POST request  but since there is not any csrf token, it was denying the access. To resolve this we have to GET in ajax request. 
    - you are trying to access the values inside request.POST without using get method, it will generate error so you have to change that.

 - Updated `favAlbum` view:
```
@login_required(login_url='fpage:login')
def favAlbum(request):
    if request.method == 'GET' and request.is_ajax():

         # use get method to access values in GET request 
        album_id = request.GET.get('album_id', None)   
        album = Album.objects.get(id=album_id)
        if album:
            _fav = album.is_favorite_album

           # if album is already favorite
            if _fav:
                album.is_favorite_album = False
            else:
                album.is_favorite_album = True

            # save album
            album.save()
            return JsonResponse({}, status=200)     # success
        else:
            # album not found
            return JsonResponse({}, status=404)   
    # invalid request
    return JsonResponse({}, status=400)
```

- Inside `index.html`:
    - You have placed the script tag inside for loop. Move it outsidde the loop and place it at the end of file just before `{% endblock %}` 
    - You can create a CSS class 'favorite' which can be added or removed to the album button if they are favourite or not. This class can be toggled inside the ajax success function. Also we are adding `data-bookmark-url` and `data-album-id` to the button so that we know the url where ajax request need to be sent and which album needs to be favourited respectively. 
``` 
....
<!-- If Album favourite, render the button with favorite class -->
{% if album.is_favorite_album %}
            <button class="btn btn-outline fas fa-heart favorite" data-bookmark-url="{% url 'fpage:fav-album' %}" data-album-id="{{ album.id }}" onclick='favouriteAlbum(this)' role="button"></button>

<!-- If Album favourite, render the button with favorite class -->
{% else %}
            <button class="btn btn-outline fas fa-heart" data-bookmark-url="{% url 'fpage:fav-album' %}" data-album-id="{{ album.id }}" onclick='favouriteAlbum(this)' role="button"></button>
{% endif %}
... 
```

- The script tag at the bottom of `index.html` just before `{% endblock %}`:

````
<!-- JS FOR FAVOURITE FEATURE -->
<script type="text/javascript">
        
        // this function is triggered by the clicking of favorite button
        // `elem` is the button which triggered the function
	function favouriteAlbum(elem) {
		$.ajax({
			type: 'GET',
			url: $(elem).attr('data-bookmark-url'),    // url where request need to be sent
			data: {
			'album_id': $(elem).attr('data-album-id'),    // album id
                },
	success: function() {
		$(elem).toggleClass('favorite');
	}
            });
        }
</script>
````

In the style.css:

```
/* Favourite Button */
.fas.fa-heart {
  color: gray;  /* Favourite button should be dull gray to when album is not favourite */
}

.favorite {
  color: red !important; /* if album is favorite */
}
```

**Comment by shrey1608** [comment]
Got it @ExpressHermes . Thanks a lot!

**Comment by shrey1608** [comment]
Please review it and merge it i want to make another PR. Thanks! @ExpressHermes @mann27

**Comment by ExpressHermes** [comment]
Good work!

**Comment by ExpressHermes** [comment]
Build similar feature for songs

**Comment by shrey1608** [comment]
@ExpressHermes Similar feature for song is created you can visit the detail page and add the song to favourite and remove the song to favourite and also you can view your favourite songs and albums

**Comment by ExpressHermes** [comment]
@shrey1608 do you want to delay points for this PR too?

**Comment by shrey1608** [comment]
yes @ExpressHermes

**Comment by shrey1608** [comment]
@mann27 Hey i wanted to know that this is the last day for making contributions for mid term evaluation or tomorrow?

**Comment by mann27** [comment]
@shrey1608 We do not know that. If you are not willing to take the risk then redeem your points today! 😅

**Comment by shrey1608** [comment]
please provide points in this PR @mann27

**Comment by mann27** [comment]
@ExpressHermes

**Comment by ExpressHermes** [comment]
give @shrey1608 150 points

**Pull request merged**
