### PR TITLE
Template error

### PR DESCRIPTION
**Pull request by sachajoy**
Resolved the template error

### CODE REVIEW

**Review by mann27 — CHANGES_REQUESTED** [review]
Do we need the .idea files?

As they are your IDE's config files. Remove them or add the .idea folder in .gitignore and re-commit the changes.

**Comment by mann27** [comment]
@sachajoy The files are not removed by adding .idea into .gitignore you have to do the following.
```
# rm all files
git rm -r --cached .
# add all files as per new .gitignore
git add .
# now, commit for new .gitignore to apply
git commit -m ".gitignore is now working"
```

**Review by mann27 — APPROVED** [review]

**Comment by mann27** [comment]
Good Work @sachajoy!

**Comment by mann27** [comment]
give @sachajoy 25 points

**Review by ExpressHermes — CHANGES_REQUESTED** [review]
@sachajoy Instead of creating a template folder in each app, create a template folder in the root folder and make sub-folders for each app. Django suggests this structure over what you have created. The template error can be solved just by adding templates localtion in the templates directory in settings.py

**Comment by sachajoy** [comment]
I added that too in settings as well

**Comment by ExpressHermes** [comment]
Yes, you did but you also reverted the changes in the folder structure that were made to make sure it follows Django suggested layout. However, you can leave it. We will fix this in future issues.

**Pull request merged**
