### PR TITLE
UI for list of songs in each Album

### PR DESCRIPTION
**Pull request by shrey1608**
image

### CODE REVIEW

**Comment by shrey1608** [comment]
Please review it @mann27  or @ExpressHermes

**Comment by ExpressHermes** [comment]
UI improvement suggestions:.

- Put everything inside container class with max-width 1000px.(if 1000px looks bad then experiment a bit with other width but it should be smaller than it is now) 

- The album information UI should be made better. Genre should have smaller font than album artist and album artist should have smaller font than Album title.


- Each song must be a card with a thumbnail image on the left (put a default svg image if the user didn't provide one), song artist.

**Comment by shrey1608** [comment]
@ExpressHermes we havent given an option to add the image to the song

**Comment by ExpressHermes** [comment]
Then just add a default svg image to each song. It will make ui better. You don't have to add the image in song model, simply render the image using frontend part.

**Comment by shrey1608** [comment]
ok so i should make cards as i made it for the albums right? @ExpressHermes

**Comment by ExpressHermes** [comment]
No, Album cards are vertical card. Song cards should be horizontal ones

**Comment by shrey1608** [comment]
okay so a thumbnail followed by song name and then the favourite heart right? and should i keep that in a table by just adding a column ? @ExpressHermes

**Comment by shrey1608** [comment]
Happy Diwali and a prosperous new year @mann27 @ExpressHermes

**Comment by ExpressHermes** [comment]
> okay so a thumbnail followed by song name and then the favourite heart right? and should i keep that in a table by just adding a column ? @ExpressHermes 

Yeah. Make this and send a pic of the UI. After that if it needs further changes,we can discuss it then.

**Comment by shrey1608** [comment]
okay!

**Comment by shrey1608** [comment]
image
Please let me know if its looking proper or not? @ExpressHermes

**Comment by ExpressHermes** [comment]
No it's not. Try something like [this](https://getbootstrap.com/docs/4.3/components/media-object/#media-list)

Make the image height equal to card height... No padding between image and card on y-axis

**Comment by shrey1608** [comment]
image
Like this @ExpressHermes ?

**Comment by mann27** [comment]
Yeah LGTM.

**Comment by shrey1608** [comment]
Please merge it @ExpressHermes

**Review by mann27 — APPROVED** [review]

**Review by ExpressHermes — APPROVED** [review]

**Comment by shrey1608** [comment]
please provide points for this @ExpressHermes or @mann27

**Comment by ExpressHermes** [comment]
give @shrey1608 75 points

**Comment by ExpressHermes** [comment]
50 points for this issue and 25 points for Album list UI

**Comment by shrey1608** [comment]
Album list UI #62

**Pull request merged**
