### PR TITLE
Connected songs and albums to User model and Home page changes

### PR DESCRIPTION
**Pull request by shrey1608**
Things connected to User model:
- we can only see albums by user in all album view
- we can only see the songs of a particular user in song-list
- when we add albums it gets added for that particular user only
- when we go in adding songs we have to select an album so we get a list of albums of that particular user'
- when we add songs it gets added for that particular user only
- when we update the album the particular album of the user gets updated
- when we update the song we get a list of albums of that particular user and gets added to that user

Home page changes:
- when you are logged in you cant see register and login button so i changed that when a user is logged in and redirected the routes for a particular feature

### CODE REVIEW

**Review by ExpressHermes — APPROVED** [review]
Good work.

**Review by mann27 — APPROVED** [review]

**Comment by shrey1608** [comment]
Please merge it @mann27 or @ExpressHermes  and give points

**Review by ExpressHermes — APPROVED** [review]

**Comment by ExpressHermes** [comment]
give @shrey1608 150 points

**Comment by shrey1608** [comment]
Thanks! @ExpressHermes @mann27

**Pull request merged**
