### PR TITLE
Implemented CRUD views for Songs model

### PR DESCRIPTION
**Pull request by shrey1608**
Added The following operations:

-    User can add a song
-    User can delete a song
-    User can Update the song
-    CRUD dashboard for song

### CODE REVIEW

**Review by ExpressHermes — APPROVED** [review]

**Review by mann27 — APPROVED** [review]

**Comment by ExpressHermes** [comment]
@shrey1608, @mann27 and I have decided that we will award 75 points on this issue since it is very similar to Albums crud issue. 

If you want to delay your points on this PR too, ping us.

**Comment by shrey1608** [comment]
@ExpressHermes Can 100 pts be given? Yes i want to delay in all PR's i will notify in the respective PR when i need the points.Thanks!

**Comment by mann27** [comment]
No, the organisers have allowed only certain value of points, else they won't go through the system and in the leaderboard.

**Comment by shrey1608** [comment]
okay no issues :)

**Comment by shrey1608** [comment]
@ExpressHermes @mann27 I think i should get 150 here as the one leading the leaderboard just added the login page and got 150 points and another 150 points for the signup .

**Comment by mann27** [comment]
@shrey1608 try not to work in regards to the leaderboard. Use this to learn new things and strengthen your skills. 

I think if others are getting points which are not at par the standards the organisers will look into it. I will also inform them to take necessary actions.

**Comment by shrey1608** [comment]
> @shrey1608 try not to work in regards to the leaderboard. Use this to learn new things and strengthen your skills.
> 
> I think if others are getting points which are not at par the standards the organisers will look into it. I will also inform them to take necessary actions.

Yes i am working to improve my skills which would be helpful in making further projects. just took a glance at the leaderboard and what all are working on so just came through this. Thanks!

**Comment by shrey1608** [comment]
please give points in this PR @mann27

**Comment by mann27** [comment]
give @shrey1608 75 points

**Pull request merged**
