### PR TITLE
Change Password and Forgot password Functionality

### PR DESCRIPTION
**Pull request by shrey1608**
Features:
- user can change password while he is logged in by going to the profile and going to forgot password
- user can reset the password while he is logged in by going to change password and then reset 
- user can also reset it from the login template

### CODE REVIEW

**Comment by shrey1608** [comment]
Please review it @mann27 @ExpressHermes

**Review by ExpressHermes — COMMENTED** [review]
@shrey1608  Is the email functionality working properly?

**Comment by shrey1608** [comment]
@ExpressHermes Yes i have created 2 options for sending the email via the admin's email to the user or to view in the console

**Comment by ExpressHermes** [comment]
Good work. I like this feature.

**Comment by shrey1608** [comment]
Thanks!

**Comment by shrey1608** [comment]
@mann27 or @ExpressHermes  Please provide points

**Comment by ExpressHermes** [comment]
give @shrey1608 75 points

**Pull request merged**
