### PR TITLE
UI for listing albums in home page

### PR DESCRIPTION
**Pull request by shrey1608**

### CODE REVIEW

**Comment by ExpressHermes** [comment]
Add a photo of the UI in description

**Comment by shrey1608** [comment]
image
@ExpressHermes

**Review by ExpressHermes — APPROVED** [review]

**Comment by shrey1608** [comment]
@mann27 or @ExpressHermes  Please provide points

**Comment by ExpressHermes** [comment]
give @shrey1608 25 points

**Comment by shrey1608** [comment]
@ExpressHermes wont this be a 50 point contribution?

**Comment by ExpressHermes** [comment]
I can't give 50 points.. I can give either 25 or 75.

**Comment by shrey1608** [comment]
umm so 2 times 25 can work? @ExpressHermes

**Comment by ExpressHermes** [comment]
@mann27

**Comment by shrey1608** [comment]
@ExpressHermes  orelse you can give 75 in Ui for listing songs so that would add upto 100

**Comment by ExpressHermes** [comment]
give @shrey1608 25 points

**Comment by shrey1608** [comment]
@ExpressHermes why you gave 25 here?

**Comment by shrey1608** [comment]
for the #22

**Comment by ExpressHermes** [comment]
I have mistakenly awarded you 25 points extra. Don't worry, I will take consider these points in the later issue.

**Comment by shrey1608** [comment]
> give @shrey1608 25 points

For #69

**Pull request merged**
