### PR TITLE
Changed relationship type between Album-User and Song User

### PR DESCRIPTION
**Pull request by shrey1608**

### CODE REVIEW

**Review by ExpressHermes — APPROVED** [review]

**Comment by shrey1608** [comment]
please merge it @ExpressHermes

**Comment by shrey1608** [comment]
@ExpressHermes please provide points

**Comment by shrey1608** [comment]
@mann27 i can redeem my points till tomorrow afternoon till 12 right?

**Comment by ExpressHermes** [comment]
give @shrey1608 5 points

**Pull request merged**
