### PR TITLE
Upadating code

### PR DESCRIPTION
**Pull request by sachajoy**

### CODE REVIEW

**Comment by ExpressHermes** [comment]
@sachajoy please provide a brief explanation of what changes you have made and what will it improve.

**Comment by sachajoy** [comment]
Added the namespace to an app URL 
If the app can be used as page:URL name 
this is according to Django documentation

**Review by ExpressHermes — APPROVED** [review]

**Comment by shrey1608** [comment]
@sachajoy  I don't think the namespace change is needed at the moment in the website/urls.py. It will be used when we have 2 apps with almost same name/purpose which conflicts the links while executing. @ExpressHermes @mann27

**Comment by ExpressHermes** [comment]
@shrey1608 For adding login/sign up feature, a new app will be added so it's not a problem. However @sachajoy avoid working on such small changes which are not needed immediately. You can take the already present issues and do these small changes while resolving those issues. When you make a commit, provide the description of any additional feature you have added and I and @mann27 will approve it.

**Comment by mann27** [comment]
Only work on the approved issues, then only points can be given. PR without an issue cannot be given the points. We will give the points for this PR but keep this in mind from now on. @sachajoy @shrey1608

**Comment by mann27** [comment]
@ExpressHermes close this giving appropriate points.

**Comment by ExpressHermes** [comment]
give @sachajoy 25 points

**Comment by sachajoy** [comment]
My points are 30 only it should be 50

**Comment by ExpressHermes** [comment]
@mann27 please check with the organizers about this.

**Comment by mann27** [comment]
> My points are 30 only it should be 50

I will look into it. Don't worry the points will get updated.

**Comment by mann27** [comment]
give @sachajoy 5 points

**Comment by mann27** [comment]
give @sachajoy 5 points

**Comment by mann27** [comment]
give @sachajoy 5 points

**Comment by mann27** [comment]
give @sachajoy 5 points

**Comment by mann27** [comment]
@sachajoy @ExpressHermes  it is resolved.

**Pull request merged**
