### PR TITLE
Implemented search feature for songs in a Album.

### PR DESCRIPTION
**Pull request by shrey1608**

### CODE REVIEW

**Review by ExpressHermes — APPROVED** [review]

**Comment by shrey1608** [comment]
please provide points @ExpressHermes

**Comment by ExpressHermes** [comment]
give @shrey1608 25 points

**Comment by shrey1608** [comment]
i think it is more than a 25 point contribution  😅  @ExpressHermes  as i implemented the logic for search and also made a landing page for it

**Comment by ExpressHermes** [comment]
The logic is one liner. Your points are based on the concepts you learned. I think I have awarded you 25 points extra on the Album list UI by mistake. You can consider those points for this issue.

**Comment by shrey1608** [comment]
okay Thanks!

**Pull request merged**
