### PR TITLE
Social Account login Feature and Delete account Feature

### PR DESCRIPTION
**Pull request by shrey1608**
- WebApp owner can add  as many social account  he/she likes. I have setup the process so he just has to add the particular social account client id and secret key and he is good to go
- Delete account feature which will delete the entire user and his account

### CODE REVIEW

**Comment by shrey1608** [comment]
please review it @ExpressHermes

**Review by ExpressHermes — APPROVED** [review]

**Comment by ExpressHermes** [comment]
Good work

**Comment by shrey1608** [comment]
please provide points for this @ExpressHermes or @mann27

**Comment by ExpressHermes** [comment]
give @shrey1608 75 points

**Comment by shrey1608** [comment]
And 25 points for the delete account feature? @ExpressHermes

**Comment by ExpressHermes** [comment]
Yes.

**Comment by ExpressHermes** [comment]
give @shrey1608 25 points

**Comment by shrey1608** [comment]
@ExpressHermes i will redeem my points for the remaining PR by 11 would you be online?

**Comment by ExpressHermes** [comment]
Don't know. You can comment on the issues when you want to redeem points, I will award points when I will come online.

**Comment by shrey1608** [comment]
ok!

**Pull request merged**
